// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type Globals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (g Globals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Globals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Globals) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}
