// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package hooks

// OauthClientCredentialsTokenOAuth2Scope - Available scopes for the oauth_client_credentials_token OAuth 2.0 scheme (clientCredentials flow).
type OauthClientCredentialsTokenOAuth2Scope string

const (

	// Read access to resources necessary to find a person by known identifiers.
	OauthClientCredentialsTokenOAuth2ScopeClientLookup OauthClientCredentialsTokenOAuth2Scope = "client:lookup"
)

// OauthUserTokenOAuth2Scope - Available scopes for the oauth_user_token OAuth 2.0 scheme (authorizationCode flow).
type OauthUserTokenOAuth2Scope string

const (

	// Read access to all relevant objects for a non-application user,  including accounts, jobs, people, transfers, and paychecks.
	OauthUserTokenOAuth2ScopeUserRead OauthUserTokenOAuth2Scope = "user:read"

	// Read and write access to all relevant objects for a non-application user, including accounts, jobs, people, transfers, and paychecks.
	OauthUserTokenOAuth2ScopeUserReadWrite OauthUserTokenOAuth2Scope = "user:read_write"
)
