// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dailypay

// Generated from OpenAPI doc version 3.0.0-beta103 and generator version 2.801.0

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/dailypay/dailypay-go-sdk/internal/config"
	"github.com/dailypay/dailypay-go-sdk/internal/globals"
	"github.com/dailypay/dailypay-go-sdk/internal/hooks"
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
	"github.com/dailypay/dailypay-go-sdk/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// DailyPay REST API server
	"https://api.{environment}.com",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// SDK - DailyPay Rest API: Embed DailyPay and On Demand Pay features into your application.
type SDK struct {
	SDKVersion string
	// The _jobs_ endpoint provides access to comprehensive information
	// about a person's employment. It enables you to retrieve details about
	// individual jobs, including information about the organization
	// they work for, status, wage rate, job title, location,
	// paycheck settings, and related links to associated accounts.
	//
	Jobs *Jobs
	// The _accounts_ endpoint provides comprehensive information about money
	// accounts. You can retrieve account details, including the
	// account's unique ID, a link to the account holder, type, subtype,
	// verification status, balance details, transfer capabilities, and
	// user-specific information such as names, routing numbers, and partial
	// account numbers.
	//
	//
	// **Functionality:** Access detailed user account information, verify
	// account balances, view transfer capabilities, and access user-specific
	// details associated with each account.
	//
	Accounts *Accounts
	// The _transfers_ endpoint allows you to initiate and track money movement.  You can access transfer details, including the transfer's unique ID, amount, currency, status, schedule, submission and resolution times, fees, and related links to the involved parties.
	//
	// **Functionality** Retrieve transfer information, monitor transfer statuses, view transfer schedules, and access relevant links for the source, destination, and origin of the transfer.
	//
	// **Important** - Account origin: a user initiated movement of money from one account to another - Paycheck origin: an automatic (system-generated) movement of money as part of payroll
	//
	Transfers *Transfers
	// The _paychecks_ endpoint provides detailed information about paychecks.
	// You can retrieve individual paycheck details, including the
	// person and job associated with the paycheck, its status, pay period,
	// expected deposit date, total debited amount, withholdings, earnings, and
	// currency.
	//
	// **Functionality:** Retrieve specific paycheck details, including payee and
	// job information, and monitor the status and financial details of each
	// paycheck.
	//
	Paychecks *Paychecks
	// The _organizations_ endpoint provides details about a business entity,
	// such as an employer, or a group of people, such as a division.
	//
	// The response includes the organization name and ID which can be used to
	// make subsequent endpoint calls related to the organization and its
	// employees.
	//
	Organizations *Organizations
	// The _people_ endpoint allows you to see information related to who owns
	// resources such as jobs and accounts.
	//
	// **Functionality:** Retrieve limited details about a person, including
	// their name, global status, and state of residence.
	//
	People *People
	// Securely tokenize personal cards for use in the accounts API.
	CardTokenization *CardTokenization
	// The _health_ endpoint provides a simple health check for the API.
	//
	// **Functionality:** Check the status of the API to ensure it is functioning
	// correctly.
	//
	Health *Health

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*SDK)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *SDK) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *SDK) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

type ServerEnvironment string

const (
	ServerEnvironmentDailypay    ServerEnvironment = "dailypay"
	ServerEnvironmentDailypayuat ServerEnvironment = "dailypayuat"
)

func (e ServerEnvironment) ToPointer() *ServerEnvironment {
	return &e
}
func (e *ServerEnvironment) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dailypay":
		fallthrough
	case "dailypayuat":
		*e = ServerEnvironment(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServerEnvironment: %v", v)
	}
}

// WithEnvironment allows setting the environment variable for url substitution
func WithEnvironment(environment ServerEnvironment) SDKOption {
	return func(sdk *SDK) {
		for idx := range sdk.sdkConfiguration.ServerVariables {
			if _, ok := sdk.sdkConfiguration.ServerVariables[idx]["environment"]; !ok {
				continue
			}

			sdk.sdkConfiguration.ServerVariables[idx]["environment"] = fmt.Sprintf("%v", environment)
		}
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security components.Security) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

// WithVersion allows setting the Version parameter for all supported operations
func WithVersion(version int64) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Globals.Version = &version
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *SDK {
	sdk := &SDK{
		SDKVersion: "0.7.5",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.7.5 2.801.0 3.0.0-beta103 github.com/dailypay/dailypay-go-sdk",
			Globals:    globals.Globals{},
			ServerList: ServerList,
			ServerVariables: []map[string]string{
				{
					"environment": "dailypay",
				},
			},
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Jobs = newJobs(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Accounts = newAccounts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Transfers = newTransfers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Paychecks = newPaychecks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Organizations = newOrganizations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.People = newPeople(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.CardTokenization = newCardTokenization(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Health = newHealth(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
