// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

var CreateGenericCardTokenServerList = []string{
	"https://payments.dailypay.com/v2",
}

type CreateGenericCardTokenRequest struct {
	// The first name or given name of the cardholder.
	FirstName string `json:"first_name"`
	// The last name or surname of the cardholder.
	LastName string `json:"last_name"`
	// The full card number without spaces or hyphenation.
	CardNumber string `json:"card_number"`
	// The four-digit year of expiration for the card.
	ExpirationYear string `json:"expiration_year"`
	// The two-digit month of the expiration date for the card.
	ExpirationMonth string `json:"expiration_month"`
	// The CVV card code.
	Cvv *string `json:"cvv,omitempty"`
	// The first line of the address associated with the card.
	AddressLineOne string `json:"address_line_one"`
	// The second line of the address associated with the card.
	AddressLineTwo *string `json:"address_line_two,omitempty"`
	// The city component of the address associated with the card.
	AddressCity string `json:"address_city"`
	// The two-letter state component of the address associated with the card.
	AddressState string `json:"address_state"`
	// The 5 digit zip-code component of the address associated with the card.
	AddressZipCode string `json:"address_zip_code"`
	// The two-letter ISO 3166 country code component of the address associated with the card.
	AddressCountry string `json:"address_country"`
}

func (c *CreateGenericCardTokenRequest) GetFirstName() string {
	if c == nil {
		return ""
	}
	return c.FirstName
}

func (c *CreateGenericCardTokenRequest) GetLastName() string {
	if c == nil {
		return ""
	}
	return c.LastName
}

func (c *CreateGenericCardTokenRequest) GetCardNumber() string {
	if c == nil {
		return ""
	}
	return c.CardNumber
}

func (c *CreateGenericCardTokenRequest) GetExpirationYear() string {
	if c == nil {
		return ""
	}
	return c.ExpirationYear
}

func (c *CreateGenericCardTokenRequest) GetExpirationMonth() string {
	if c == nil {
		return ""
	}
	return c.ExpirationMonth
}

func (c *CreateGenericCardTokenRequest) GetCvv() *string {
	if c == nil {
		return nil
	}
	return c.Cvv
}

func (c *CreateGenericCardTokenRequest) GetAddressLineOne() string {
	if c == nil {
		return ""
	}
	return c.AddressLineOne
}

func (c *CreateGenericCardTokenRequest) GetAddressLineTwo() *string {
	if c == nil {
		return nil
	}
	return c.AddressLineTwo
}

func (c *CreateGenericCardTokenRequest) GetAddressCity() string {
	if c == nil {
		return ""
	}
	return c.AddressCity
}

func (c *CreateGenericCardTokenRequest) GetAddressState() string {
	if c == nil {
		return ""
	}
	return c.AddressState
}

func (c *CreateGenericCardTokenRequest) GetAddressZipCode() string {
	if c == nil {
		return ""
	}
	return c.AddressZipCode
}

func (c *CreateGenericCardTokenRequest) GetAddressCountry() string {
	if c == nil {
		return ""
	}
	return c.AddressCountry
}

// CreateGenericCardTokenResponseBody - Returns an opaque string representing the card details.
type CreateGenericCardTokenResponseBody struct {
	// This token should be supplied in the `generic_token` field when creating a TransferAccount with
	// `transfer_account_type` of DebitCard using the Extend API "Create a transfer account" endpoint.
	//
	Token string `json:"token"`
}

func (c *CreateGenericCardTokenResponseBody) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

type CreateGenericCardTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns an opaque string representing the card details.
	//
	Object *CreateGenericCardTokenResponseBody
}

func (c *CreateGenericCardTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateGenericCardTokenResponse) GetObject() *CreateGenericCardTokenResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
