// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type CreateAccountGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (c CreateAccountGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAccountGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAccountGlobals) GetVersion() *int64 {
	if c == nil {
		return nil
	}
	return c.Version
}

type CreateAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the account object.
	AccountData *components.AccountData
}

func (c *CreateAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAccountResponse) GetAccountData() *components.AccountData {
	if c == nil {
		return nil
	}
	return c.AccountData
}
