// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type DeleteAccountGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (d DeleteAccountGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAccountGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAccountGlobals) GetVersion() *int64 {
	if d == nil {
		return nil
	}
	return d.Version
}

type DeleteAccountRequest struct {
	// Unique UUID of the Account.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
}

func (d *DeleteAccountRequest) GetAccountID() string {
	if d == nil {
		return ""
	}
	return d.AccountID
}

type DeleteAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
