// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type GetHealthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a healthcheck document
	Health200 *components.Health200
}

func (g *GetHealthResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetHealthResponse) GetHealth200() *components.Health200 {
	if g == nil {
		return nil
	}
	return g.Health200
}
