// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type ListOrganizationsGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (l ListOrganizationsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationsGlobals) GetVersion() *int64 {
	if l == nil {
		return nil
	}
	return l.Version
}

type ListOrganizationsRequest struct {
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	FilterBy *string `queryParam:"style=form,explode=true,name=filter"`
}

func (l *ListOrganizationsRequest) GetFilterBy() *string {
	if l == nil {
		return nil
	}
	return l.FilterBy
}

type ListOrganizationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a list of organization objects that match the filter. If no organizations match the filter, the resulting collection will be empty. If no filter is provider, the resulting collection will include all accessible organizations.
	OrganizationsData *components.OrganizationsData
}

func (l *ListOrganizationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOrganizationsResponse) GetOrganizationsData() *components.OrganizationsData {
	if l == nil {
		return nil
	}
	return l.OrganizationsData
}
