// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type ListAccountsGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (l ListAccountsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAccountsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAccountsGlobals) GetVersion() *int64 {
	if l == nil {
		return nil
	}
	return l.Version
}

type ListAccountsRequest struct {
	// Limit the results to documents related to a specific person
	FilterPersonID *string `queryParam:"style=form,explode=true,name=filter[person.id]"`
	// Limit the results to documents matching the specified account type.
	FilterAccountType *components.FilterAccountType `queryParam:"style=form,explode=true,name=filter[account_type]"`
	// Limit the results to documents matching the specified account subtype.
	FilterSubtype *string `queryParam:"style=form,explode=true,name=filter[subtype]"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	FilterBy *string `queryParam:"style=form,explode=true,name=filter"`
}

func (l *ListAccountsRequest) GetFilterPersonID() *string {
	if l == nil {
		return nil
	}
	return l.FilterPersonID
}

func (l *ListAccountsRequest) GetFilterAccountType() *components.FilterAccountType {
	if l == nil {
		return nil
	}
	return l.FilterAccountType
}

func (l *ListAccountsRequest) GetFilterSubtype() *string {
	if l == nil {
		return nil
	}
	return l.FilterSubtype
}

func (l *ListAccountsRequest) GetFilterBy() *string {
	if l == nil {
		return nil
	}
	return l.FilterBy
}

type ListAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the account object.
	AccountsData *components.AccountsData
}

func (l *ListAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAccountsResponse) GetAccountsData() *components.AccountsData {
	if l == nil {
		return nil
	}
	return l.AccountsData
}
