// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type ReadTransferGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (r ReadTransferGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadTransferGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadTransferGlobals) GetVersion() *int64 {
	if r == nil {
		return nil
	}
	return r.Version
}

type ReadTransferRequest struct {
	// Add related resources to the response.
	//
	// The value of the include parameter must be a comma-separated (U+002C COMMA, “,”) list of relationship paths.
	//
	Include *string `queryParam:"style=form,explode=true,name=include"`
	// Unique ID of the transfer
	TransferID string `pathParam:"style=simple,explode=false,name=transfer_id"`
}

func (r *ReadTransferRequest) GetInclude() *string {
	if r == nil {
		return nil
	}
	return r.Include
}

func (r *ReadTransferRequest) GetTransferID() string {
	if r == nil {
		return ""
	}
	return r.TransferID
}

type ReadTransferResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the newly created transfer object.
	TransferData *components.TransferData
}

func (r *ReadTransferResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadTransferResponse) GetTransferData() *components.TransferData {
	if r == nil {
		return nil
	}
	return r.TransferData
}
