// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type ReadJobGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (r ReadJobGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadJobGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReadJobGlobals) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

type ReadJobRequest struct {
	// Unique ID of the job
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (o *ReadJobRequest) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

type ReadJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the job object.
	JobData *components.JobData
}

func (o *ReadJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadJobResponse) GetJobData() *components.JobData {
	if o == nil {
		return nil
	}
	return o.JobData
}
