// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

type ReadOrganizationGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (r ReadOrganizationGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadOrganizationGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadOrganizationGlobals) GetVersion() *int64 {
	if r == nil {
		return nil
	}
	return r.Version
}

type ReadOrganizationRequest struct {
	// Unique ID of the organization
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
}

func (r *ReadOrganizationRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

type ReadOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns details about an organization.
	OrganizationData *components.OrganizationData
}

func (r *ReadOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadOrganizationResponse) GetOrganizationData() *components.OrganizationData {
	if r == nil {
		return nil
	}
	return r.OrganizationData
}
