// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountDataInput struct {
	Data AccountResourceInput `json:"data"`
}

func (a *AccountDataInput) GetData() AccountResourceInput {
	if a == nil {
		return AccountResourceInput{}
	}
	return a.Data
}
