// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountsData - Returns the account object.
type AccountsData struct {
	Data []AccountResourceOutput `json:"data"`
}

func (a *AccountsData) GetData() []AccountResourceOutput {
	if a == nil {
		return []AccountResourceOutput{}
	}
	return a.Data
}
