// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountDataOutput - Returns the account object.
type AccountDataOutput struct {
	Data AccountResourceOutput `json:"data"`
}

func (a *AccountDataOutput) GetData() AccountResourceOutput {
	if a == nil {
		return AccountResourceOutput{}
	}
	return a.Data
}
