// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountCreateAttributesType string

const (
	AccountCreateAttributesTypeAccountCreateAttributesCard       AccountCreateAttributesType = "AccountCreateAttributes_Card"
	AccountCreateAttributesTypeAccountCreateAttributesDepository AccountCreateAttributesType = "AccountCreateAttributes_Depository"
)

// AccountCreateAttributes - The details of the account.
type AccountCreateAttributes struct {
	AccountCreateAttributesCard       *AccountCreateAttributesCard       `queryParam:"inline,name=AccountCreateAttributes" union:"member"`
	AccountCreateAttributesDepository *AccountCreateAttributesDepository `queryParam:"inline,name=AccountCreateAttributes" union:"member"`

	Type AccountCreateAttributesType
}

func CreateAccountCreateAttributesAccountCreateAttributesCard(accountCreateAttributesCard AccountCreateAttributesCard) AccountCreateAttributes {
	typ := AccountCreateAttributesTypeAccountCreateAttributesCard

	return AccountCreateAttributes{
		AccountCreateAttributesCard: &accountCreateAttributesCard,
		Type:                        typ,
	}
}

func CreateAccountCreateAttributesAccountCreateAttributesDepository(accountCreateAttributesDepository AccountCreateAttributesDepository) AccountCreateAttributes {
	typ := AccountCreateAttributesTypeAccountCreateAttributesDepository

	return AccountCreateAttributes{
		AccountCreateAttributesDepository: &accountCreateAttributesDepository,
		Type:                              typ,
	}
}

func (u *AccountCreateAttributes) UnmarshalJSON(data []byte) error {

	var accountCreateAttributesCard AccountCreateAttributesCard = AccountCreateAttributesCard{}
	if err := utils.UnmarshalJSON(data, &accountCreateAttributesCard, "", true, nil); err == nil {
		u.AccountCreateAttributesCard = &accountCreateAttributesCard
		u.Type = AccountCreateAttributesTypeAccountCreateAttributesCard
		return nil
	}

	var accountCreateAttributesDepository AccountCreateAttributesDepository = AccountCreateAttributesDepository{}
	if err := utils.UnmarshalJSON(data, &accountCreateAttributesDepository, "", true, nil); err == nil {
		u.AccountCreateAttributesDepository = &accountCreateAttributesDepository
		u.Type = AccountCreateAttributesTypeAccountCreateAttributesDepository
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AccountCreateAttributes", string(data))
}

func (u AccountCreateAttributes) MarshalJSON() ([]byte, error) {
	if u.AccountCreateAttributesCard != nil {
		return utils.MarshalJSON(u.AccountCreateAttributesCard, "", true)
	}

	if u.AccountCreateAttributesDepository != nil {
		return utils.MarshalJSON(u.AccountCreateAttributesDepository, "", true)
	}

	return nil, errors.New("could not marshal union type AccountCreateAttributes: all fields are null")
}
