// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountRelationship struct {
	Data AccountIdentifier `json:"data"`
}

func (a AccountRelationship) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRelationship) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"data"}); err != nil {
		return err
	}
	return nil
}

func (a *AccountRelationship) GetData() AccountIdentifier {
	if a == nil {
		return AccountIdentifier{}
	}
	return a.Data
}
