// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountResource struct {
	// The unique identifier of the Account.
	ID string `json:"id"`
	// The type of the resource. Always `accounts`.
	type_ string `const:"accounts" json:"type"`
	// The details of the account.
	Attributes    AccountAttributes    `json:"attributes"`
	Links         AccountLinks         `json:"links"`
	Relationships AccountRelationships `json:"relationships"`
}

func (a AccountResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountResource) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccountResource) GetType() string {
	return "accounts"
}

func (a *AccountResource) GetAttributes() AccountAttributes {
	if a == nil {
		return AccountAttributes{}
	}
	return a.Attributes
}

func (a *AccountResource) GetLinks() AccountLinks {
	if a == nil {
		return AccountLinks{}
	}
	return a.Links
}

func (a *AccountResource) GetRelationships() AccountRelationships {
	if a == nil {
		return AccountRelationships{}
	}
	return a.Relationships
}
