// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountIdentifier struct {
	type_ string `const:"accounts" json:"type"`
	ID    string `json:"id"`
}

func (a AccountIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (a *AccountIdentifier) GetType() string {
	return "accounts"
}

func (a *AccountIdentifier) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}
