// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountLinks struct {
	// The URI for the account
	Self string `json:"self"`
}

func (a *AccountLinks) GetSelf() string {
	if a == nil {
		return ""
	}
	return a.Self
}
