// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountResourceInput struct {
	// The type of the resource. Always `accounts`.
	type_ string `const:"accounts" json:"type"`
	// The details of the account.
	Attributes    AccountAttributesInput `json:"attributes"`
	Relationships AccountRelationships   `json:"relationships"`
}

func (a AccountResourceInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountResourceInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"type", "attributes", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (a *AccountResourceInput) GetType() string {
	return "accounts"
}

func (a *AccountResourceInput) GetAttributes() AccountAttributesInput {
	if a == nil {
		return AccountAttributesInput{}
	}
	return a.Attributes
}

func (a *AccountResourceInput) GetRelationships() AccountRelationships {
	if a == nil {
		return AccountRelationships{}
	}
	return a.Relationships
}
