// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountRelationships struct {
	Person PersonRelationship `json:"person"`
}

func (a *AccountRelationships) GetPerson() PersonRelationship {
	if a == nil {
		return PersonRelationship{}
	}
	return a.Person
}
