// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountsData - Returns the account object.
type AccountsData struct {
	Data []AccountResource `json:"data"`
}

func (a *AccountsData) GetData() []AccountResource {
	if a == nil {
		return []AccountResource{}
	}
	return a.Data
}
