// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountCreateResource struct {
	// The type of the resource. Always `accounts`.
	type_ string `const:"accounts" json:"type"`
	// The details of the account.
	Attributes    AccountCreateAttributes `json:"attributes"`
	Relationships AccountRelationships    `json:"relationships"`
}

func (a AccountCreateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountCreateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountCreateResource) GetType() string {
	return "accounts"
}

func (a *AccountCreateResource) GetAttributes() AccountCreateAttributes {
	if a == nil {
		return AccountCreateAttributes{}
	}
	return a.Attributes
}

func (a *AccountCreateResource) GetRelationships() AccountRelationships {
	if a == nil {
		return AccountRelationships{}
	}
	return a.Relationships
}
