// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountData - Returns the account object.
type AccountData struct {
	Data AccountResource `json:"data"`
}

func (a *AccountData) GetData() AccountResource {
	if a == nil {
		return AccountResource{}
	}
	return a.Data
}
