// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountCreateData struct {
	Data AccountCreateResource `json:"data"`
}

func (a *AccountCreateData) GetData() AccountCreateResource {
	if a == nil {
		return AccountCreateResource{}
	}
	return a.Data
}
