// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type AccountResourceOutput struct {
	// The unique identifier of the Account.
	ID string `json:"id"`
	// The type of the resource. Always `accounts`.
	type_ string `const:"accounts" json:"type"`
	// The details of the account.
	Attributes    AccountAttributesOutput `json:"attributes"`
	Links         AccountLinks            `json:"links"`
	Relationships AccountRelationships    `json:"relationships"`
}

func (a AccountResourceOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountResourceOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountResourceOutput) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccountResourceOutput) GetType() string {
	return "accounts"
}

func (a *AccountResourceOutput) GetAttributes() AccountAttributesOutput {
	if a == nil {
		return AccountAttributesOutput{}
	}
	return a.Attributes
}

func (a *AccountResourceOutput) GetLinks() AccountLinks {
	if a == nil {
		return AccountLinks{}
	}
	return a.Links
}

func (a *AccountResourceOutput) GetRelationships() AccountRelationships {
	if a == nil {
		return AccountRelationships{}
	}
	return a.Relationships
}
