// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ErrorUnexpectedErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorUnexpectedErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (e *ErrorUnexpectedErrorLinks) GetAbout() *string {
	if e == nil {
		return nil
	}
	return e.About
}

// ErrorUnexpectedErrorSource - Location in the request that may have caused the error.
type ErrorUnexpectedErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (e *ErrorUnexpectedErrorSource) GetParameter() *string {
	if e == nil {
		return nil
	}
	return e.Parameter
}

func (e *ErrorUnexpectedErrorSource) GetPointer() *string {
	if e == nil {
		return nil
	}
	return e.Pointer
}

func (e *ErrorUnexpectedErrorSource) GetHeader() *string {
	if e == nil {
		return nil
	}
	return e.Header
}

// ErrorUnexpectedErrorMeta - Additional information about the error.
type ErrorUnexpectedErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (e *ErrorUnexpectedErrorMeta) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorUnexpectedErrorMeta) GetTraceID() *string {
	if e == nil {
		return nil
	}
	return e.TraceID
}

// ErrorUnexpectedErrorCode - A code that indicates what went wrong.
type ErrorUnexpectedErrorCode string

const (
	ErrorUnexpectedErrorCodeUnexpectedError ErrorUnexpectedErrorCode = "UNEXPECTED_ERROR"
)

func (e ErrorUnexpectedErrorCode) ToPointer() *ErrorUnexpectedErrorCode {
	return &e
}
func (e *ErrorUnexpectedErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNEXPECTED_ERROR":
		*e = ErrorUnexpectedErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorUnexpectedErrorCode: %v", v)
	}
}

type ErrorUnexpectedError struct {
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorUnexpectedErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorUnexpectedErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorUnexpectedErrorMeta `json:"meta"`
	// A code that indicates what went wrong.
	Code ErrorUnexpectedErrorCode `json:"code"`
}

func (e *ErrorUnexpectedError) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *ErrorUnexpectedError) GetDetail() string {
	if e == nil {
		return ""
	}
	return e.Detail
}

func (e *ErrorUnexpectedError) GetLinks() ErrorUnexpectedErrorLinks {
	if e == nil {
		return ErrorUnexpectedErrorLinks{}
	}
	return e.Links
}

func (e *ErrorUnexpectedError) GetSource() *ErrorUnexpectedErrorSource {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *ErrorUnexpectedError) GetMeta() ErrorUnexpectedErrorMeta {
	if e == nil {
		return ErrorUnexpectedErrorMeta{}
	}
	return e.Meta
}

func (e *ErrorUnexpectedError) GetCode() ErrorUnexpectedErrorCode {
	if e == nil {
		return ErrorUnexpectedErrorCode("")
	}
	return e.Code
}
