// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorConflictErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorConflictErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (e *ErrorConflictErrorLinks) GetAbout() *string {
	if e == nil {
		return nil
	}
	return e.About
}

// ErrorConflictErrorSource - Location in the request that may have caused the error.
type ErrorConflictErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (e *ErrorConflictErrorSource) GetParameter() *string {
	if e == nil {
		return nil
	}
	return e.Parameter
}

func (e *ErrorConflictErrorSource) GetPointer() *string {
	if e == nil {
		return nil
	}
	return e.Pointer
}

func (e *ErrorConflictErrorSource) GetHeader() *string {
	if e == nil {
		return nil
	}
	return e.Header
}

// ErrorConflictErrorMeta - Additional information about the error.
type ErrorConflictErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (e *ErrorConflictErrorMeta) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorConflictErrorMeta) GetTraceID() *string {
	if e == nil {
		return nil
	}
	return e.TraceID
}

type ErrorConflictError struct {
	// A code that indicates what went wrong.
	Code string `json:"code"`
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorConflictErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorConflictErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorConflictErrorMeta `json:"meta"`
}

func (e *ErrorConflictError) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorConflictError) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *ErrorConflictError) GetDetail() string {
	if e == nil {
		return ""
	}
	return e.Detail
}

func (e *ErrorConflictError) GetLinks() ErrorConflictErrorLinks {
	if e == nil {
		return ErrorConflictErrorLinks{}
	}
	return e.Links
}

func (e *ErrorConflictError) GetSource() *ErrorConflictErrorSource {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *ErrorConflictError) GetMeta() ErrorConflictErrorMeta {
	if e == nil {
		return ErrorConflictErrorMeta{}
	}
	return e.Meta
}
