// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorBadRequestErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorBadRequestErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (e *ErrorBadRequestErrorLinks) GetAbout() *string {
	if e == nil {
		return nil
	}
	return e.About
}

// ErrorBadRequestErrorSource - Location in the request that may have caused the error.
type ErrorBadRequestErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (e *ErrorBadRequestErrorSource) GetParameter() *string {
	if e == nil {
		return nil
	}
	return e.Parameter
}

func (e *ErrorBadRequestErrorSource) GetPointer() *string {
	if e == nil {
		return nil
	}
	return e.Pointer
}

func (e *ErrorBadRequestErrorSource) GetHeader() *string {
	if e == nil {
		return nil
	}
	return e.Header
}

// ErrorBadRequestErrorMeta - Additional information about the error.
type ErrorBadRequestErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (e *ErrorBadRequestErrorMeta) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorBadRequestErrorMeta) GetTraceID() *string {
	if e == nil {
		return nil
	}
	return e.TraceID
}

type ErrorBadRequestError struct {
	// A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
	Code string `json:"code"`
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorBadRequestErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorBadRequestErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorBadRequestErrorMeta `json:"meta"`
}

func (e *ErrorBadRequestError) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorBadRequestError) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *ErrorBadRequestError) GetDetail() string {
	if e == nil {
		return ""
	}
	return e.Detail
}

func (e *ErrorBadRequestError) GetLinks() ErrorBadRequestErrorLinks {
	if e == nil {
		return ErrorBadRequestErrorLinks{}
	}
	return e.Links
}

func (e *ErrorBadRequestError) GetSource() *ErrorBadRequestErrorSource {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *ErrorBadRequestError) GetMeta() ErrorBadRequestErrorMeta {
	if e == nil {
		return ErrorBadRequestErrorMeta{}
	}
	return e.Meta
}
