// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorAccountCreateErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorAccountCreateErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (e *ErrorAccountCreateErrorLinks) GetAbout() *string {
	if e == nil {
		return nil
	}
	return e.About
}

// ErrorAccountCreateErrorSource - Location in the request that may have caused the error.
type ErrorAccountCreateErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (e *ErrorAccountCreateErrorSource) GetParameter() *string {
	if e == nil {
		return nil
	}
	return e.Parameter
}

func (e *ErrorAccountCreateErrorSource) GetPointer() *string {
	if e == nil {
		return nil
	}
	return e.Pointer
}

func (e *ErrorAccountCreateErrorSource) GetHeader() *string {
	if e == nil {
		return nil
	}
	return e.Header
}

// ErrorAccountCreateErrorMeta - Additional information about the error.
type ErrorAccountCreateErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (e *ErrorAccountCreateErrorMeta) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorAccountCreateErrorMeta) GetTraceID() *string {
	if e == nil {
		return nil
	}
	return e.TraceID
}

type ErrorAccountCreateError struct {
	// A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
	Code string `json:"code"`
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorAccountCreateErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorAccountCreateErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorAccountCreateErrorMeta `json:"meta"`
}

func (e *ErrorAccountCreateError) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorAccountCreateError) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *ErrorAccountCreateError) GetDetail() string {
	if e == nil {
		return ""
	}
	return e.Detail
}

func (e *ErrorAccountCreateError) GetLinks() ErrorAccountCreateErrorLinks {
	if e == nil {
		return ErrorAccountCreateErrorLinks{}
	}
	return e.Links
}

func (e *ErrorAccountCreateError) GetSource() *ErrorAccountCreateErrorSource {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *ErrorAccountCreateError) GetMeta() ErrorAccountCreateErrorMeta {
	if e == nil {
		return ErrorAccountCreateErrorMeta{}
	}
	return e.Meta
}
