// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FundingSourcesRelationship struct {
	Data []FundingSourceIdentifier `json:"data"`
}

func (f *FundingSourcesRelationship) GetData() []FundingSourceIdentifier {
	if f == nil {
		return []FundingSourceIdentifier{}
	}
	return f.Data
}
