// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FundingSourceRelationships struct {
	Source   PaycheckRelationship `json:"source"`
	Transfer TransferRelationship `json:"transfer"`
}

func (f *FundingSourceRelationships) GetSource() PaycheckRelationship {
	if f == nil {
		return PaycheckRelationship{}
	}
	return f.Source
}

func (f *FundingSourceRelationships) GetTransfer() TransferRelationship {
	if f == nil {
		return TransferRelationship{}
	}
	return f.Transfer
}
