// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type FundingSourceIdentifier struct {
	type_ string `const:"funding_sources" json:"type"`
	ID    string `json:"id"`
}

func (f FundingSourceIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FundingSourceIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FundingSourceIdentifier) GetType() string {
	return "funding_sources"
}

func (f *FundingSourceIdentifier) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}
