// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FundingSourceAttributes struct {
	// A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
	Amount int64 `json:"amount"`
	// A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
	Currency string `json:"currency"`
}

func (f *FundingSourceAttributes) GetAmount() int64 {
	if f == nil {
		return 0
	}
	return f.Amount
}

func (f *FundingSourceAttributes) GetCurrency() string {
	if f == nil {
		return ""
	}
	return f.Currency
}
