// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

// FundingSourceResource - A source describes how transfers with an origin of EARNINGS_BALANCE account are funded.
type FundingSourceResource struct {
	ID            string                     `json:"id"`
	type_         string                     `const:"funding_sources" json:"type"`
	Attributes    FundingSourceAttributes    `json:"attributes"`
	Relationships FundingSourceRelationships `json:"relationships"`
}

func (f FundingSourceResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FundingSourceResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FundingSourceResource) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FundingSourceResource) GetType() string {
	return "funding_sources"
}

func (f *FundingSourceResource) GetAttributes() FundingSourceAttributes {
	if f == nil {
		return FundingSourceAttributes{}
	}
	return f.Attributes
}

func (f *FundingSourceResource) GetRelationships() FundingSourceRelationships {
	if f == nil {
		return FundingSourceRelationships{}
	}
	return f.Relationships
}
