// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Health200 - Returns a healthcheck document
type Health200 struct {
	// The status of the API
	Status string `json:"status"`
	// The version of the API
	Version string `json:"version"`
}

func (h *Health200) GetStatus() string {
	if h == nil {
		return ""
	}
	return h.Status
}

func (h *Health200) GetVersion() string {
	if h == nil {
		return ""
	}
	return h.Version
}
