// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type JobIdentifier struct {
	type_ string `const:"jobs" json:"type"`
	ID    string `json:"id"`
}

func (j JobIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JobIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JobIdentifier) GetType() string {
	return "jobs"
}

func (j *JobIdentifier) GetID() string {
	if j == nil {
		return ""
	}
	return j.ID
}
