// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobLinks struct {
	Self string `json:"self"`
}

func (j *JobLinks) GetSelf() string {
	if j == nil {
		return ""
	}
	return j.Self
}
