// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobRelationships - The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
type JobRelationships struct {
	Person       PersonRelationship       `json:"person"`
	Organization OrganizationRelationship `json:"organization"`
	// The `DEPOSITORY` account to which paychecks from this job will attempt to be deposited.
	DirectDepositDefaultDepository *AccountRelationship `json:"direct_deposit_default_depository,omitempty"`
	// The `CARD` account to which paychecks from this job will attempt to be deposited, if the `DEPOSITORY` account fails.
	DirectDepositDefaultCard *AccountRelationship `json:"direct_deposit_default_card,omitempty"`
}

func (j *JobRelationships) GetPerson() PersonRelationship {
	if j == nil {
		return PersonRelationship{}
	}
	return j.Person
}

func (j *JobRelationships) GetOrganization() OrganizationRelationship {
	if j == nil {
		return OrganizationRelationship{}
	}
	return j.Organization
}

func (j *JobRelationships) GetDirectDepositDefaultDepository() *AccountRelationship {
	if j == nil {
		return nil
	}
	return j.DirectDepositDefaultDepository
}

func (j *JobRelationships) GetDirectDepositDefaultCard() *AccountRelationship {
	if j == nil {
		return nil
	}
	return j.DirectDepositDefaultCard
}
