// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobRelationships - The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
type JobRelationships struct {
	Person                         PersonRelationshipReadOnly `json:"person"`
	Organization                   OrganizationRelationship   `json:"organization"`
	DirectDepositDefaultDepository *AccountRelationship       `json:"direct_deposit_default_depository,omitempty"`
	DirectDepositDefaultCard       *AccountRelationship       `json:"direct_deposit_default_card,omitempty"`
}

func (j *JobRelationships) GetPerson() PersonRelationshipReadOnly {
	if j == nil {
		return PersonRelationshipReadOnly{}
	}
	return j.Person
}

func (j *JobRelationships) GetOrganization() OrganizationRelationship {
	if j == nil {
		return OrganizationRelationship{}
	}
	return j.Organization
}

func (j *JobRelationships) GetDirectDepositDefaultDepository() *AccountRelationship {
	if j == nil {
		return nil
	}
	return j.DirectDepositDefaultDepository
}

func (j *JobRelationships) GetDirectDepositDefaultCard() *AccountRelationship {
	if j == nil {
		return nil
	}
	return j.DirectDepositDefaultCard
}
