// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobRelationship struct {
	Data JobIdentifier `json:"data"`
}

func (j *JobRelationship) GetData() JobIdentifier {
	if j == nil {
		return JobIdentifier{}
	}
	return j.Data
}
