// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

// JobResource - A job describes the financial relationship between a person and an organization.
type JobResource struct {
	type_      string        `const:"jobs" json:"type"`
	ID         string        `json:"id"`
	Attributes JobAttributes `json:"attributes"`
	Links      JobLinks      `json:"links"`
	// The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
	Relationships JobRelationships `json:"relationships"`
}

func (j JobResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JobResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, []string{"type", "id", "attributes", "links", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (j *JobResource) GetType() string {
	return "jobs"
}

func (j *JobResource) GetID() string {
	if j == nil {
		return ""
	}
	return j.ID
}

func (j *JobResource) GetAttributes() JobAttributes {
	if j == nil {
		return JobAttributes{}
	}
	return j.Attributes
}

func (j *JobResource) GetLinks() JobLinks {
	if j == nil {
		return JobLinks{}
	}
	return j.Links
}

func (j *JobResource) GetRelationships() JobRelationships {
	if j == nil {
		return JobRelationships{}
	}
	return j.Relationships
}
