// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobRelationshipsInput - The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
type JobRelationshipsInput struct {
	DirectDepositDefaultDepository *AccountRelationship `json:"direct_deposit_default_depository,omitempty"`
	DirectDepositDefaultCard       *AccountRelationship `json:"direct_deposit_default_card,omitempty"`
}

func (j *JobRelationshipsInput) GetDirectDepositDefaultDepository() *AccountRelationship {
	if j == nil {
		return nil
	}
	return j.DirectDepositDefaultDepository
}

func (j *JobRelationshipsInput) GetDirectDepositDefaultCard() *AccountRelationship {
	if j == nil {
		return nil
	}
	return j.DirectDepositDefaultCard
}
