// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobsData - Returns a list of job objects.
type JobsData struct {
	Data []JobResource `json:"data"`
}

func (j *JobsData) GetData() []JobResource {
	if j == nil {
		return []JobResource{}
	}
	return j.Data
}
