// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaychecksData - Returns the paycheck object.
type PaychecksData struct {
	Data []PaycheckResource `json:"data"`
}

func (p *PaychecksData) GetData() []PaycheckResource {
	if p == nil {
		return []PaycheckResource{}
	}
	return p.Data
}
