// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaycheckRelationships struct {
	Person PersonRelationship `json:"person"`
	Job    JobRelationship    `json:"job"`
}

func (p *PaycheckRelationships) GetPerson() PersonRelationship {
	if p == nil {
		return PersonRelationship{}
	}
	return p.Person
}

func (p *PaycheckRelationships) GetJob() JobRelationship {
	if p == nil {
		return JobRelationship{}
	}
	return p.Job
}
