// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaycheckData - Returns the paycheck object.
type PaycheckData struct {
	Data PaycheckResource `json:"data"`
}

func (p *PaycheckData) GetData() PaycheckResource {
	if p == nil {
		return PaycheckResource{}
	}
	return p.Data
}
