// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type PaycheckIdentifier struct {
	type_ string `const:"paychecks" json:"type"`
	ID    string `json:"id"`
}

func (p PaycheckIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaycheckIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (p *PaycheckIdentifier) GetType() string {
	return "paychecks"
}

func (p *PaycheckIdentifier) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}
