// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaycheckLinks struct {
	Self string `json:"self"`
}

func (p *PaycheckLinks) GetSelf() string {
	if p == nil {
		return ""
	}
	return p.Self
}
