// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type PaycheckResource struct {
	type_         string                `const:"paychecks" json:"type"`
	ID            string                `json:"id"`
	Attributes    PaycheckAttributes    `json:"attributes"`
	Links         PaycheckLinks         `json:"links"`
	Relationships PaycheckRelationships `json:"relationships"`
}

func (p PaycheckResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaycheckResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaycheckResource) GetType() string {
	return "paychecks"
}

func (p *PaycheckResource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaycheckResource) GetAttributes() PaycheckAttributes {
	if p == nil {
		return PaycheckAttributes{}
	}
	return p.Attributes
}

func (p *PaycheckResource) GetLinks() PaycheckLinks {
	if p == nil {
		return PaycheckLinks{}
	}
	return p.Links
}

func (p *PaycheckResource) GetRelationships() PaycheckRelationships {
	if p == nil {
		return PaycheckRelationships{}
	}
	return p.Relationships
}
