// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type PersonResource struct {
	type_ string `const:"people" json:"type"`
	ID    string `json:"id"`
	// A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
	Attributes PersonAttributes `json:"attributes"`
	Links      PersonLinks      `json:"links"`
}

func (p PersonResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PersonResource) GetType() string {
	return "people"
}

func (p *PersonResource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PersonResource) GetAttributes() PersonAttributes {
	if p == nil {
		return PersonAttributes{}
	}
	return p.Attributes
}

func (p *PersonResource) GetLinks() PersonLinks {
	if p == nil {
		return PersonLinks{}
	}
	return p.Links
}
