// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PersonRelationship struct {
	Data PersonIdentifier `json:"data"`
}

func (p *PersonRelationship) GetData() PersonIdentifier {
	if p == nil {
		return PersonIdentifier{}
	}
	return p.Data
}
