// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PersonLinks struct {
	// The URI for the user
	Self string `json:"self"`
}

func (p *PersonLinks) GetSelf() string {
	if p == nil {
		return ""
	}
	return p.Self
}
