// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PersonDataInput struct {
	Data PersonResourceInput `json:"data"`
}

func (p *PersonDataInput) GetData() PersonResourceInput {
	if p == nil {
		return PersonResourceInput{}
	}
	return p.Data
}
