// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

// PersonUpdateAttributes - A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
type PersonUpdateAttributes struct {
	// The two-letter abbreviation for the state in which the person resides, if located in the United States.  This is used for regulatory compliance purposes.
	//
	StateOfResidence string `json:"state_of_residence"`
}

func (p *PersonUpdateAttributes) GetStateOfResidence() string {
	if p == nil {
		return ""
	}
	return p.StateOfResidence
}

type PersonUpdateResource struct {
	type_ string `const:"people" json:"type"`
	ID    string `json:"id"`
	// A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
	PersonUpdateAttributes PersonUpdateAttributes `json:"attributes"`
}

func (p PersonUpdateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonUpdateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PersonUpdateResource) GetType() string {
	return "people"
}

func (p *PersonUpdateResource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PersonUpdateResource) GetPersonUpdateAttributes() PersonUpdateAttributes {
	if p == nil {
		return PersonUpdateAttributes{}
	}
	return p.PersonUpdateAttributes
}

type PersonUpdateData struct {
	PersonUpdateResource PersonUpdateResource `json:"data"`
}

func (p *PersonUpdateData) GetPersonUpdateResource() PersonUpdateResource {
	if p == nil {
		return PersonUpdateResource{}
	}
	return p.PersonUpdateResource
}
