// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PersonAttributesInput - A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
type PersonAttributesInput struct {
	// The two-letter abbreviation for the state in which the person resides, if located in the United States.  This is used for regulatory compliance purposes.
	//
	StateOfResidence *string `json:"state_of_residence,omitempty"`
}

func (p *PersonAttributesInput) GetStateOfResidence() *string {
	if p == nil {
		return nil
	}
	return p.StateOfResidence
}
