// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type PersonIdentifier struct {
	type_ string `const:"people" json:"type"`
	ID    string `json:"id"`
}

func (p PersonIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PersonIdentifier) GetType() string {
	return "people"
}

func (p *PersonIdentifier) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}
