// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PersonData - Returns the person object.
type PersonData struct {
	Data PersonResource `json:"data"`
}

func (p *PersonData) GetData() PersonResource {
	if p == nil {
		return PersonResource{}
	}
	return p.Data
}
