// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type PersonResourceInput struct {
	type_ string `const:"people" json:"type"`
	ID    string `json:"id"`
	// A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
	Attributes PersonAttributesInput `json:"attributes"`
}

func (p PersonResourceInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonResourceInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type", "id", "attributes"}); err != nil {
		return err
	}
	return nil
}

func (p *PersonResourceInput) GetType() string {
	return "people"
}

func (p *PersonResourceInput) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PersonResourceInput) GetAttributes() PersonAttributesInput {
	if p == nil {
		return PersonAttributesInput{}
	}
	return p.Attributes
}
