// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type SchemeOauthClientCredentialsToken struct {
	ClientID     string `security:"name=clientID"`
	ClientSecret string `security:"name=clientSecret"`
	TokenURL     string `default:"https://auth.dailypay.com/oauth2/token"`
}

func (s SchemeOauthClientCredentialsToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemeOauthClientCredentialsToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemeOauthClientCredentialsToken) GetClientID() string {
	if s == nil {
		return ""
	}
	return s.ClientID
}

func (s *SchemeOauthClientCredentialsToken) GetClientSecret() string {
	if s == nil {
		return ""
	}
	return s.ClientSecret
}

func (s *SchemeOauthClientCredentialsToken) GetTokenURL() string {
	if s == nil {
		return ""
	}
	return s.TokenURL
}
