// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	OauthClientCredentialsToken *SchemeOauthClientCredentialsToken `security:"scheme,type=oauth2,subtype=client_credentials"`
	OauthUserToken              *string                            `security:"scheme,type=oauth2,name=Authorization"`
}

func (s *Security) GetOauthClientCredentialsToken() *SchemeOauthClientCredentialsToken {
	if s == nil {
		return nil
	}
	return s.OauthClientCredentialsToken
}

func (s *Security) GetOauthUserToken() *string {
	if s == nil {
		return nil
	}
	return s.OauthUserToken
}
