// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransferData - Returns the newly created transfer object.
type TransferData struct {
	Data     TransferResource        `json:"data"`
	Included []FundingSourceResource `json:"included,omitempty"`
}

func (t *TransferData) GetData() TransferResource {
	if t == nil {
		return TransferResource{}
	}
	return t.Data
}

func (t *TransferData) GetIncluded() []FundingSourceResource {
	if t == nil {
		return nil
	}
	return t.Included
}
