// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferCreateRelationships struct {
	// User-created transfers must originate from an Account with `account_type` `EARNINGS_BALANCE`.
	//
	Origin AccountRelationship `json:"origin"`
	// The account to which funds are transferred.
	//
	// User-created transfers should have a destination Account with `account_type` `DEPOSITORY` or `CARD`.
	//
	Destination *AccountRelationship `json:"destination,omitempty"`
	Person      *PersonRelationship  `json:"person,omitempty"`
}

func (t *TransferCreateRelationships) GetOrigin() AccountRelationship {
	if t == nil {
		return AccountRelationship{}
	}
	return t.Origin
}

func (t *TransferCreateRelationships) GetDestination() *AccountRelationship {
	if t == nil {
		return nil
	}
	return t.Destination
}

func (t *TransferCreateRelationships) GetPerson() *PersonRelationship {
	if t == nil {
		return nil
	}
	return t.Person
}
