// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferRelationship struct {
	Data TransferIdentifier `json:"data"`
}

func (t *TransferRelationship) GetData() TransferIdentifier {
	if t == nil {
		return TransferIdentifier{}
	}
	return t.Data
}
