// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransferCreateRelationships - The relationships between the transfer and other resources, including the destination account, the origination account, and the person who initiated the transfer.
type TransferCreateRelationships struct {
	Origin      AccountRelationship `json:"origin"`
	Destination AccountRelationship `json:"destination"`
	Person      PersonRelationship  `json:"person"`
}

func (t *TransferCreateRelationships) GetOrigin() AccountRelationship {
	if t == nil {
		return AccountRelationship{}
	}
	return t.Origin
}

func (t *TransferCreateRelationships) GetDestination() AccountRelationship {
	if t == nil {
		return AccountRelationship{}
	}
	return t.Destination
}

func (t *TransferCreateRelationships) GetPerson() PersonRelationship {
	if t == nil {
		return PersonRelationship{}
	}
	return t.Person
}
