// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type TransferCreateResource struct {
	type_ string `const:"transfers" json:"type"`
	// The unique identifier of the transfer. Any UUID version is valid, lower-cased.
	ID *string `json:"id,omitempty"`
	// An object representing a transfer of money from one account to another.
	// Created when a person takes an advance against a future paycheck, or on a daily basis
	// when we update estimated earnings based on current employment.
	//
	Attributes    TransferAttributesInput     `json:"attributes"`
	Relationships TransferCreateRelationships `json:"relationships"`
}

func (t TransferCreateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferCreateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"type", "attributes", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (t *TransferCreateResource) GetType() string {
	return "transfers"
}

func (t *TransferCreateResource) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TransferCreateResource) GetAttributes() TransferAttributesInput {
	if t == nil {
		return TransferAttributesInput{}
	}
	return t.Attributes
}

func (t *TransferCreateResource) GetRelationships() TransferCreateRelationships {
	if t == nil {
		return TransferCreateRelationships{}
	}
	return t.Relationships
}
