// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferCreateData struct {
	Data TransferCreateResource `json:"data"`
}

func (t *TransferCreateData) GetData() TransferCreateResource {
	if t == nil {
		return TransferCreateResource{}
	}
	return t.Data
}
