// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferCreateRelationships struct {
	Origin      AccountRelationship  `json:"origin"`
	Destination *AccountRelationship `json:"destination,omitempty"`
	Person      *PersonRelationship  `json:"person,omitempty"`
}

func (t *TransferCreateRelationships) GetOrigin() AccountRelationship {
	if t == nil {
		return AccountRelationship{}
	}
	return t.Origin
}

func (t *TransferCreateRelationships) GetDestination() *AccountRelationship {
	if t == nil {
		return nil
	}
	return t.Destination
}

func (t *TransferCreateRelationships) GetPerson() *PersonRelationship {
	if t == nil {
		return nil
	}
	return t.Person
}
