// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransfersData - A list of transfer objects.
type TransfersData struct {
	Data     []TransferResource      `json:"data"`
	Included []FundingSourceResource `json:"included,omitempty"`
}

func (t *TransfersData) GetData() []TransferResource {
	if t == nil {
		return []TransferResource{}
	}
	return t.Data
}

func (t *TransfersData) GetIncluded() []FundingSourceResource {
	if t == nil {
		return nil
	}
	return t.Included
}
