// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type TransferIdentifier struct {
	type_ string `const:"transfers" json:"type"`
	ID    string `json:"id"`
}

func (t TransferIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransferIdentifier) GetType() string {
	return "transfers"
}

func (t *TransferIdentifier) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}
