// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dailypay/dailypay-go-sdk/internal/utils"
)

type TransferResource struct {
	type_ string `const:"transfers" json:"type"`
	ID    string `json:"id"`
	// An object representing a transfer of money from one account to another.
	// Created when a person takes an advance against a future paycheck, or on a daily basis
	// when we update estimated earnings based on current employment.
	//
	Attributes    TransferAttributes    `json:"attributes"`
	Links         TransferLinks         `json:"links"`
	Relationships TransferRelationships `json:"relationships"`
}

func (t TransferResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransferResource) GetType() string {
	return "transfers"
}

func (t *TransferResource) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TransferResource) GetAttributes() TransferAttributes {
	if t == nil {
		return TransferAttributes{}
	}
	return t.Attributes
}

func (t *TransferResource) GetLinks() TransferLinks {
	if t == nil {
		return TransferLinks{}
	}
	return t.Links
}

func (t *TransferResource) GetRelationships() TransferRelationships {
	if t == nil {
		return TransferRelationships{}
	}
	return t.Relationships
}
