// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferLinks struct {
	Self string `json:"self"`
}

func (t *TransferLinks) GetSelf() string {
	if t == nil {
		return ""
	}
	return t.Self
}
