// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"undefined/models/components"
)

// ErrorForbidden - Not authorized to perform this operation
type ErrorForbidden struct {
	// A list of errors that occurred.
	Errors   []components.ErrorForbiddenError `json:"errors"`
	HTTPMeta components.HTTPMetadata          `json:"-"`
}

var _ error = &ErrorForbidden{}

func (e *ErrorForbidden) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
