// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"undefined/models/components"
)

// ErrorBadRequest - Bad Request
type ErrorBadRequest struct {
	// A list of errors that occurred.
	Errors   []components.ErrorBadRequestError `json:"errors"`
	HTTPMeta components.HTTPMetadata           `json:"-"`
}

var _ error = &ErrorBadRequest{}

func (e *ErrorBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
