// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"undefined/models/components"
)

// ErrorUnauthorized - Invalid authentication credentials
type ErrorUnauthorized struct {
	// A list of errors that occurred.
	Errors   []components.ErrorUnauthorizedError `json:"errors"`
	HTTPMeta components.HTTPMetadata             `json:"-"`
}

var _ error = &ErrorUnauthorized{}

func (e *ErrorUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
