// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/dailypay/dailypay-go-sdk/models/components"
)

// ErrorConflict - A conflict occurred with the current state of the resource
type ErrorConflict struct {
	// A list of errors that occurred.
	Errors   []components.ErrorConflictError `json:"errors"`
	HTTPMeta components.HTTPMetadata         `json:"-"`
}

var _ error = &ErrorConflict{}

func (e *ErrorConflict) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
