// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"undefined/models/components"
)

// TransferCreateError - The request contained an error
type TransferCreateError struct {
	// A list of errors that occurred.
	Errors   []components.ErrorTransferCreateError `json:"errors"`
	HTTPMeta components.HTTPMetadata               `json:"-"`
}

var _ error = &TransferCreateError{}

func (e *TransferCreateError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
