workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    local:
        inputs:
            - location: https://s3.amazonaws.com/dp-devportal-images/sdk/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
targets:
    go:
        target: go
        source: local
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
